---
# tasks file for haproxy

- name: my package
  package:
        name: "haproxy"
        state: present

- name: my conf file copy
  template:
        src: "haproxy.cfg.j2"
        dest: "/etc/haproxy/haproxy.cfg"

- name: my service
  service:
        name: "haproxy"
        state: started
        enabled: yes
- name: my firewall service
  service:
        name: "firewalld"
        state: started
        enabled: yes



- name: my firwall
  firewalld:
       port: 80/tcp
       permanent: yes
       state: enabled
       immediate: yes


